package io.printer;

/**
 * Converts a String generated by a Printer to another format.
 */
public interface Converter {
	
	/**
	 * Returns a converted Printer generated String.
	 * @param s String generated by a Printer
	 * @return Converted String
	 */
	public String convert(String s);
}
